#!/usr/bin/env bash
# a Bash script that displays a list of currently running processes.


ps aux --forest | awk '{
    printf "%-10s %-5s %-4s %-6s %-5s %-8s %-6s %-6s %-8s %-s", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10;
    for (i=11; i<=NF; i++) {
        printf " %s", $i;
    }
    print "";
}'
