#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and displays bad luck at 4th and displays good luck at 8th anddisplays Best School

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
