#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
h=0; 
while [ $h -le 12 ];
do
	echo "Hour: $h"
	s=0
	while [ $s -le 59 ];
	do
		echo $s
		((s++))
	done
	((h++))
done
