#!/usr/bin/env bash
# Bash script to list directory contents with only the part after the first dash
for file in *;
do
	if [[ ! "$file" =~ ^\..* && -f "$file" ]];
	then
		trimmed_name=$(echo "$file" | cut -d'-' -f2-)
		echo "$trimmed_name"
	fi
done
